export const ACTIONS = {
	CHANGE_TITLE: "CHANGE_TITLE",
	FETCH_AGENT_DATA: "FETCH_AGENT_DATA",
	FETCH_AGENT_DATA_FULFILLED: "FETCH_AGENT_DATA_FULFILLED",
	FETCH_AGENT_DATA_FAILED: "FETCH_AGENT_DATA_FAILED"
};